# Generated by Django 4.1.2 on 2022-10-06 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='category',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Auto'), (2, 'Pickup'), (3, 'Comercial'), (4, 'Suv'), (5, 'Crossover')], null=True),
        ),
    ]
