# Generated by Django 4.1.2 on 2022-10-06 23:48

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_group_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='version',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='version',
            name='photo',
            field=versatileimagefield.fields.VersatileImageField(blank=True, help_text='Foto del relevamiento', max_length=200, null=True, upload_to='imagenes/arbolado'),
        ),
        migrations.AddField(
            model_name='version',
            name='photo_ppoi',
            field=versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20, verbose_name='Image PPOI'),
        ),
    ]
