# Generated by Django 4.1.2 on 2022-10-06 23:48

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_remove_version_photo_url_version_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='photo',
            field=versatileimagefield.fields.VersatileImageField(blank=True, help_text='Foto del relevamiento', max_length=200, null=True, upload_to='images/cars'),
        ),
    ]
